import SwiftUI

/// A translation a screen already has for a word, ready to answer a tap without the model. The
/// dictionary form comes along so the sheet can show what the inflected word in the text is.
struct KnownTranslation: Equatable {
    /// Where the answer came from, so the sheet can say so.
    enum Source: Equatable {
        /// The glossary generated with the story.
        case glossary
        /// A word this learner looked up earlier and that was kept with the story.
        case earlierLookup
    }

    /// The glossary's own headword, e.g. "die Katze" for a tapped "Katzen".
    var german: String
    var english: String
    var source: Source = .glossary
}

/// A word the learner tapped to inspect (translate + optionally save).
struct InspectedWord: Identifiable, Equatable {
    let id = UUID()
    let word: String
    var translation: String?
    var loading: Bool
    /// True while the wait is the model being pulled into memory rather than the translation
    /// itself — the several-second pause on the first lookup after opening the app. Worth naming
    /// in the sheet, because it looks like a hang otherwise and it only happens once.
    var loadingModel: Bool = false
    var saved: Bool
    /// Set when the translation was answered from something the screen already had (the story's
    /// glossary, or an earlier lookup) rather than generated by the model.
    var glossary: KnownTranslation?
}

/// Anything that can drive the word inspector sheet: the conversation engine and the story
/// reader's `WordInspectorModel` both conform, so `WordInspectorSheet` works over either.
@MainActor
protocol WordInspecting: AnyObject {
    var inspectedWord: InspectedWord? { get }
    func saveInspectedWord()
    func dismissInspector()
}

/// The shared core of "double-tap a word": trim it and translate it 1:1 on-device.
enum SingleWordTranslator {
    /// Trim surrounding punctuation/whitespace but keep umlauts and hyphens.
    static func cleanWord(_ s: String) -> String {
        var allowed = CharacterSet.letters
        allowed.insert(charactersIn: "-'’")
        return s.trimmingCharacters(in: allowed.inverted)
    }

    /// True when `model` is already in memory, so a tap answers without the load wait.
    @MainActor
    static func isReady(_ model: MLXModel, in mlxService: MLXGenerationService) -> Bool {
        mlxService.isModelLoaded && mlxService.currentModel == model
    }

    /// Translate a single German word, loading `model` first if it isn't in memory. `onModelReady`
    /// fires once the weights are in memory and the wait becomes the translation itself, so the
    /// caller can stop saying "loading the model".
    @MainActor
    static func translate(
        _ word: String,
        mlxService: MLXGenerationService,
        model: MLXModel,
        onModelReady: (@MainActor () -> Void)? = nil
    ) async -> String? {
        if !isReady(model, in: mlxService) {
            await mlxService.loadModel(model)
            guard isReady(model, in: mlxService) else { return nil }
        }
        onModelReady?()
        do {
            let raw = try await mlxService.generateText(
                system: ConversationPrompts.translationSystemPrompt,
                user: ConversationPrompts.translationUserPrompt(german: word),
                model: model,
                maxTokens: 48
            )
            let cleaned = ConversationPrompts.cleanTranslation(raw)
            return cleaned.isEmpty ? nil : cleaned
        } catch {
            return nil
        }
    }
}

/// A self-contained inspector driver for screens without a conversation engine (story reading).
/// The owner supplies where saved words go via `onSave`.
@Observable
@MainActor
final class WordInspectorModel: WordInspecting {
    private let mlxService: MLXGenerationService
    private let model: MLXModel
    private let isWordSaved: (String) -> Bool
    private let onSave: (_ german: String, _ english: String?) -> Void
    private let onLookup: (_ german: String, _ english: String) -> Void

    private(set) var inspectedWord: InspectedWord?

    /// Translations the screen already has, keyed by the lowercased form the word appears in. The
    /// story reader fills this from the story's glossary: those words answer instantly, and without
    /// pulling a model into memory just to re-translate what's already on screen.
    var knownTranslations: [String: KnownTranslation] = [:]

    /// `onLookup` reports each word the model actually had to translate, for the owner to keep.
    init(
        mlxService: MLXGenerationService,
        model: MLXModel,
        isWordSaved: @escaping (String) -> Bool = { _ in false },
        onSave: @escaping (_ german: String, _ english: String?) -> Void,
        onLookup: @escaping (_ german: String, _ english: String) -> Void = { _, _ in }
    ) {
        self.mlxService = mlxService
        self.model = model
        self.isWordSaved = isWordSaved
        self.onSave = onSave
        self.onLookup = onLookup
    }

    func inspect(_ raw: String) {
        let word = SingleWordTranslator.cleanWord(raw)
        guard !word.isEmpty else { return }
        if let known = knownTranslations[word.lowercased()], !known.english.isEmpty {
            inspectedWord = InspectedWord(
                word: word,
                translation: known.english,
                loading: false,
                saved: isWordSaved(word),
                glossary: known
            )
            return
        }
        inspectedWord = InspectedWord(
            word: word,
            translation: nil,
            loading: true,
            loadingModel: !SingleWordTranslator.isReady(model, in: mlxService),
            saved: isWordSaved(word)
        )
        Task {
            let translation = await SingleWordTranslator.translate(
                word,
                mlxService: mlxService,
                model: model,
                onModelReady: { [weak self] in
                    guard let self, inspectedWord?.word == word else { return }
                    inspectedWord?.loadingModel = false
                }
            )
            // Only apply if the inspector is still showing the same word.
            if inspectedWord?.word == word {
                inspectedWord?.translation = translation
                inspectedWord?.loading = false
                inspectedWord?.loadingModel = false
            }
            // Keep the answer: the next tap on this word is then instant and, more to the point,
            // costs no model load — including after the app has been restarted, since the owner
            // persists what it's handed.
            if let translation, !translation.isEmpty {
                knownTranslations[word.lowercased()] = KnownTranslation(
                    german: word, english: translation, source: .earlierLookup
                )
                onLookup(word, translation)
            }
        }
    }

    func saveInspectedWord() {
        guard let inspected = inspectedWord, !inspected.saved else { return }
        onSave(inspected.word, inspected.translation)
        inspectedWord?.saved = true
    }

    func dismissInspector() { inspectedWord = nil }
}

/// Shown when the user taps a word — its translation, hear-it, and a save-to-library action.
struct WordInspectorSheet: View {
    let source: any WordInspecting
    /// One line under the actions explaining where saved words end up in this context.
    let footer: String

    @Environment(\.appTheme) private var appTheme

    var body: some View {
        NavigationStack {
            Group {
                if let inspected = source.inspectedWord {
                    content(inspected)
                } else {
                    Color.clear
                }
            }
            .background {
                if appTheme != .klar { ThemedBackground().ignoresSafeArea() }
            }
            .navigationTitle("Word")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .confirmationAction) {
                    Button("Done") { source.dismissInspector() }
                }
            }
            .presentationDetents([.height(300)])
        }
    }

    @ViewBuilder
    private func content(_ inspected: InspectedWord) -> some View {
        VStack(alignment: .leading, spacing: 16) {
            Text(inspected.word)
                .font(.largeTitle.weight(.semibold))
                .fixedSize(horizontal: false, vertical: true)

            if inspected.loading {
                VStack(alignment: .leading, spacing: 4) {
                    HStack(spacing: 8) {
                        ProgressView()
                        Text(inspected.loadingModel ? "Getting the model ready…" : "Translating…")
                            .foregroundStyle(.secondary)
                    }
                    if inspected.loadingModel {
                        Text("The first word after opening the app waits for the model to load into memory. After that, lookups are quick.")
                            .font(.caption2)
                            .foregroundStyle(.tertiary)
                            .fixedSize(horizontal: false, vertical: true)
                    }
                }
            } else if let translation = inspected.translation, !translation.isEmpty {
                VStack(alignment: .leading, spacing: 4) {
                    Text(translation).font(.title3).foregroundStyle(.secondary)
                    if let glossary = inspected.glossary {
                        // Name the dictionary form when the text used an inflected one ("Katzen"
                        // tapped, "die Katze" listed).
                        let sameWord = glossary.german.caseInsensitiveCompare(inspected.word) == .orderedSame
                        switch glossary.source {
                        case .glossary:
                            Label(sameWord
                                  ? "From this story's glossary"
                                  : "From this story's glossary: \(glossary.german)",
                                  systemImage: "character.book.closed")
                                .font(.caption2)
                                .foregroundStyle(.tertiary)
                        case .earlierLookup:
                            Label("You looked this up earlier", systemImage: "clock.arrow.circlepath")
                                .font(.caption2)
                                .foregroundStyle(.tertiary)
                        }
                    }
                }
            } else {
                Text("No translation found.").font(.callout).foregroundStyle(.secondary)
            }

            HStack(spacing: 16) {
                Button { SpeechService.shared.speak(inspected.word) } label: {
                    Label("Hear it", systemImage: "speaker.wave.2.fill")
                }
                .buttonStyle(.bordered)

                if inspected.saved {
                    Label("Saved", systemImage: "checkmark.circle.fill")
                        .foregroundStyle(.green)
                } else {
                    Button { source.saveInspectedWord() } label: {
                        Label("Save to flashcard library", systemImage: "rectangle.stack.badge.plus")
                    }
                    .buttonStyle(.borderedProminent)
                    .disabled(inspected.loading)
                }
            }

            Text(footer)
                .font(.caption2).foregroundStyle(.secondary)

            Spacer()
        }
        .padding()
        .frame(maxWidth: .infinity, alignment: .leading)
    }
}
